/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IncidentLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getIncident"
      | "getTotalIncidents"
      | "incidentExistsCheck"
      | "incidentHashes"
      | "incidents"
      | "recordIncident"
      | "transferAdmin"
      | "updateStatus"
      | "verifyIncident"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "IncidentRecorded"
      | "StatusUpdated"
      | "VerificationAdded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getIncident",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalIncidents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "incidentExistsCheck",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incidentHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incidents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordIncident",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIncident",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIncident",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalIncidents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incidentExistsCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incidentHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "incidents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordIncident",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyIncident",
    data: BytesLike
  ): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IncidentRecordedEvent {
  export type InputTuple = [hash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [hash: string, timestamp: bigint];
  export interface OutputObject {
    hash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [
    hash: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    oldStatus: bigint,
    newStatus: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    hash: string;
    oldStatus: bigint;
    newStatus: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationAddedEvent {
  export type InputTuple = [
    hash: BytesLike,
    positive: boolean,
    positiveCount: BigNumberish,
    negativeCount: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    positive: boolean,
    positiveCount: bigint,
    negativeCount: bigint
  ];
  export interface OutputObject {
    hash: string;
    positive: boolean;
    positiveCount: bigint;
    negativeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IncidentLedger extends BaseContract {
  connect(runner?: ContractRunner | null): IncidentLedger;
  waitForDeployment(): Promise<this>;

  interface: IncidentLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getIncident: TypedContractMethod<
    [_hash: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        timestamp: bigint;
        status: bigint;
        positiveVerifications: bigint;
        negativeVerifications: bigint;
      }
    ],
    "view"
  >;

  getTotalIncidents: TypedContractMethod<[], [bigint], "view">;

  incidentExistsCheck: TypedContractMethod<
    [_hash: BytesLike],
    [boolean],
    "view"
  >;

  incidentHashes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  incidents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        hash: string;
        timestamp: bigint;
        status: bigint;
        positiveVerifications: bigint;
        negativeVerifications: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  recordIncident: TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [_hash: BytesLike, _newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyIncident: TypedContractMethod<
    [_hash: BytesLike, _positive: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getIncident"
  ): TypedContractMethod<
    [_hash: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        timestamp: bigint;
        status: bigint;
        positiveVerifications: bigint;
        negativeVerifications: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalIncidents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "incidentExistsCheck"
  ): TypedContractMethod<[_hash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "incidentHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "incidents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        hash: string;
        timestamp: bigint;
        status: bigint;
        positiveVerifications: bigint;
        negativeVerifications: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordIncident"
  ): TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [_hash: BytesLike, _newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyIncident"
  ): TypedContractMethod<
    [_hash: BytesLike, _positive: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "IncidentRecorded"
  ): TypedContractEvent<
    IncidentRecordedEvent.InputTuple,
    IncidentRecordedEvent.OutputTuple,
    IncidentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationAdded"
  ): TypedContractEvent<
    VerificationAddedEvent.InputTuple,
    VerificationAddedEvent.OutputTuple,
    VerificationAddedEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "IncidentRecorded(bytes32,uint256)": TypedContractEvent<
      IncidentRecordedEvent.InputTuple,
      IncidentRecordedEvent.OutputTuple,
      IncidentRecordedEvent.OutputObject
    >;
    IncidentRecorded: TypedContractEvent<
      IncidentRecordedEvent.InputTuple,
      IncidentRecordedEvent.OutputTuple,
      IncidentRecordedEvent.OutputObject
    >;

    "StatusUpdated(bytes32,uint8,uint8,uint256)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;

    "VerificationAdded(bytes32,bool,uint256,uint256)": TypedContractEvent<
      VerificationAddedEvent.InputTuple,
      VerificationAddedEvent.OutputTuple,
      VerificationAddedEvent.OutputObject
    >;
    VerificationAdded: TypedContractEvent<
      VerificationAddedEvent.InputTuple,
      VerificationAddedEvent.OutputTuple,
      VerificationAddedEvent.OutputObject
    >;
  };
}
